server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: planning
          uri: http://localhost:8081
          predicates:
            - Path=/courses/**/approvalSystems/** 
        - id: operation
          uri: http://localhost:8082
          predicates:
            - Path=/instructors/**/venues/**/classes/** /courseLists/**
        - id: marketing
          uri: http://localhost:8083
          predicates:
            - Path=/webSites/** 
        - id: supporting
          uri: http://localhost:8084
          predicates:
            - Path=/calendars/** 
        - id: enrollment
          uri: http://localhost:8085
          predicates:
            - Path=/enrollments/** 
        - id: recommendation
          uri: http://localhost:8086
          predicates:
            - Path=/추천시스템/** 
        - id: newbc
          uri: http://localhost:8087
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: planning
          uri: http://planning:8080
          predicates:
            - Path=/courses/**/approvalSystems/** 
        - id: operation
          uri: http://operation:8080
          predicates:
            - Path=/instructors/**/venues/**/classes/** /courseLists/**
        - id: marketing
          uri: http://marketing:8080
          predicates:
            - Path=/webSites/** 
        - id: supporting
          uri: http://supporting:8080
          predicates:
            - Path=/calendars/** 
        - id: enrollment
          uri: http://enrollment:8080
          predicates:
            - Path=/enrollments/** 
        - id: recommendation
          uri: http://recommendation:8080
          predicates:
            - Path=/추천시스템/** 
        - id: newbc
          uri: http://newbc:8080
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080