---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning
  labels:
    app: planning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planning
  template:
    metadata:
      labels:
        app: planning
    spec:
      containers:
        - name: planning
          image: username/planning:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: operation
  labels:
    app: operation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operation
  template:
    metadata:
      labels:
        app: operation
    spec:
      containers:
        - name: operation
          image: username/operation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing
  labels:
    app: marketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketing
  template:
    metadata:
      labels:
        app: marketing
    spec:
      containers:
        - name: marketing
          image: username/marketing:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: supporting
  labels:
    app: supporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supporting
  template:
    metadata:
      labels:
        app: supporting
    spec:
      containers:
        - name: supporting
          image: username/supporting:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment
  labels:
    app: enrollment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment
  template:
    metadata:
      labels:
        app: enrollment
    spec:
      containers:
        - name: enrollment
          image: username/enrollment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
        - name: recommendation
          image: username/recommendation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: newbc
  labels:
    app: newbc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newbc
  template:
    metadata:
      labels:
        app: newbc
    spec:
      containers:
        - name: newbc
          image: username/newbc:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: planning
  labels:
    app: planning
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: planning


---


apiVersion: v1
kind: Service
metadata:
  name: operation
  labels:
    app: operation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: operation


---


apiVersion: v1
kind: Service
metadata:
  name: marketing
  labels:
    app: marketing
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: marketing


---


apiVersion: v1
kind: Service
metadata:
  name: supporting
  labels:
    app: supporting
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: supporting


---


apiVersion: v1
kind: Service
metadata:
  name: enrollment
  labels:
    app: enrollment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: enrollment


---


apiVersion: v1
kind: Service
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: recommendation


---


apiVersion: v1
kind: Service
metadata:
  name: newbc
  labels:
    app: newbc
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: newbc

