apiVersion: apps/v1
kind: Deployment
metadata:
  name: newbc
  labels:
    app: newbc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newbc
  template:
    metadata:
      labels:
        app: newbc
    spec:
      containers:
        - name: newbc
          image: username/newbc:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5