apiVersion: apps/v1
kind: Deployment
metadata:
  name: operation
  labels:
    app: operation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operation
  template:
    metadata:
      labels:
        app: operation
    spec:
      containers:
        - name: operation
          image: username/operation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5